### ISSUE TITLE
TODO: after merging #33

### ISSUE THREAD

**Issue by 3cp** [dumberjs/dumber-gist#35]
after merging #33

- [ ] (Not Possible) migrate from registry.npmjs.cf to data.jsdelivr.com
- [x] simplify client-service-worker build, maybe merge the gulp task to client/gulpfile.js.
- [x] update deploy.sh
- [x] update production nginx conf if needed.

**Comment by 3cp** [comment]
Too bad, data.jsdelivr.com does not provide full npm registry. https://github.com/jsdelivr/data.jsdelivr.com#list-package-versions

The versions list in the payload does not have dependencies which is critical for resolving algorithm.
